[package]
name = "tree_sitter_example"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "tree_sitter_example"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.25.0"
tree-sitter = "0.20.8"
tree-sitter-json = "0.19.0"
